name: WhatIsThis
main: io.github.steve4744.whatisthis.WhatIsThis
author: steve4744
version: ${project.version}
api-version: 1.21.3
description: Displays the name of the block or entity that you are looking at.
softdepend: [Slimefun, Nova, ItemsAdder, PlaceholderAPI, Oraxen, Nexo, MythicMobs, Citizens]

commands:
  whatisthis:
    aliases: [wt, wit, whatisthat]
    description: WhatIsThis commands

permissions:
  whatisthis.use:
    description: used to control who can use whatisthis and where.
    default: true
  whatisthis.admin:
    description: needed for admin commands
    default: op